--monitor=,preferred,auto,1.0
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1.0",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@120",
    position = "1920x0",
    scale = "1.0",
    bitdepth = 10,
})

-- Source: ./keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinds")
-- Source: ./startenv.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostartenv")
-- Source: ./dms/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
-- require("dms.colors")

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("myBezier", { type = "bezier", points = { { 0.01, 1.0 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 5,
    bezier = "myBezier",
    style = "slide",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "slide right 80%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "slide 50%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 5,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 2,
        col = {
          active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
          inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        --layout = dwindle
        --layout = master
        layout = "scrolling",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 12,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true,
        default_split_ratio = 1.1,
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    scrolling = {
        fullscreen_on_one_column = true,
        column_width = 0.5,
        focus_fit_method = 1, --When a column is focused, what method should be used to bring it into view. 0 = center, 1 = fit 
        follow_focus = true,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
        direction = "right",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "hu",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        --xset r rate 200 35
        repeat_rate = 35,
        repeat_delay = 200,
        touchpad = {
            natural_scroll = false,
        },
    },
    cursor = {
        inactive_timeout = 30,
        no_hardware_cursors = true,
    },
  hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

})

