
wallpaper {
    monitor = eDP-1
    path = ~/walls/KawaiiWaifu/sketchy/
    fit_mode = contain
    timeout = 900
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/walls/KawaiiWaifu/sketchy/
    fit_mode = contain
    timeout = 900
}

splash = false

#wallpaper {
#    monitor = 
#    path = ~/fallback.jxl
#    fit_mode = cover
#}
