--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local terminal = "kitty"
local fileManager = "kitty -e yazi"
local browser = "librewolf"
--$browser = brave
--$menu = wofi --show drun
--$menu = rofi -show drun
--$menu = rofi -show drun -run-command "uwsm app -- {cmd}"
--$menu = fuzzel "--launch-prefix=uwsm app --"
local menu = "fuzzel --launch-prefix=app2unit"
--local menu = "dms ipc call spotlight toggle"
local powermenu = "dms ipc call powermenu toggle"
local reload_waybar = "pkill waybar; waybar &"
local snip = "grim -g \"$(slurp)\" - | swappy -f -"

--###################
--## KEYBINDINGSS ###
--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER"

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
--bind = $mainMod, Return, exec, uwsm app -- $terminal
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("app2unit -- " .. terminal))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
--bind = $mainMod, W, exec, [workspace 2] uwsm app -- $browser
--bind = $mainMod, W, exec, uwsm app -- $browser
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("app2unit -- " .. browser))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("dms ipc call wallpaper next"))
--bind = $mainMod Alt, W, exec, waypaper --random
hl.bind(mainMod .. " + M", hl.dsp.exit())
--bind = $mainMod, E, exec, [workspace 3] uwsm app -- $fileManager
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("[workspace 3] app2unit -- " .. fileManager))
--bind = $mainMod, T, exec, [workspace 4] uwsm app -- thunderbird
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("[workspace 4] app2unit -- thunderbird"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(powermenu))
--bind = $mainMod Alt, L, exec, hyprlock
hl.bind(mainMod .. " + ALT + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(snip))
--hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

-- Move focus with mainMod + vim arrow keys
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Opacity for inactive windows
hl.window_rule({
    match = {
        float = 0,
        focus = 0,
    },
    opacity = "0.9 0.9",
})

hl.window_rule({
    match = {
        class = "^(blueman-manager)$",
    },
    float = true,
})

-- Open DMS windows as floating by default
hl.window_rule({
    match = {
        class = "^(org.quickshell)$",
    },
    float = true,
})

-- GNOME apps
--windowrule = rounding 12, border_size 0, match:class ^(org\.gnome\.)
-- Terminal app - no borders
--windowrule = border_size 0, match:class ^(kitty)$

--Audio and brightness controls
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + period", hl.dsp.layout("move +col"))
hl.bind(mainMod .. " + comma", hl.dsp.layout("move -col"))
hl.bind(mainMod .. " + SHIFT + period", hl.dsp.layout("swapcol r"))
hl.bind(mainMod .. " + SHIFT + comma", hl.dsp.layout("swapcol l"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.layout("colresize +conf"))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.layout("colresize -conf"))

hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
