-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local WR = "WallRizz -n -e -s 81x25 -d " .. wallpaperDir .. " " .. themeMode .. " -f \"STD.setenv('enableBlur',true)\""
local WallRizz = "kitty -1 -o allow_remote_control=yes -o background_opacity=" .. overlay_window_opacity .. " --title=WallRizz " .. WR
local WallRizzRandom = "kitty -1 -o allow_remote_control=yes --class=hidden --title=hidden " .. WR .. " -r"

-- WallRizz Grid View
hl.window_rule({
    match = {
        title = "^(WallRizz)$",
    },
    float = true,
    size = "70% 70%",
    animation = "slide top",
    pin = true,
    center = true,
    border_size = 10,
    rounding = 20,
})

-- WallRizz Array View
hl.window_rule({
    match = {
        title = "^(WallRizz)$",
    },
    float = true,
    animation = "slide top",
    pin = true,
    center = true,
    size = "70% 30%",
    border_size = 10,
    rounding = 20,
})

-- WallRizz Stack View
hl.window_rule({
    match = {
        title = "^(WallRizz)$",
    },
    float = true,
    size = "363 981",
    move = "80% 5%",
    animation = "slide right",
    pin = true,
    border_size = 10,
})

-- Key binds
hl.bind("f3", hl.dsp.exec_cmd(WallRizz), { drag = true })
hl.bind(mainMod .. " + f3", hl.dsp.exec_cmd(WallRizzRandom), { drag = true })
