#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = udiskie &
#exec-once = swaync &
#exec-once = waybar & 
#exec-once = awww & waypaper --restore #hyprpaper & 
#exec-once = qs & #launch my own quickshell bar
#exec-once = app2unit -- dms run &
#exec-once = app2unit -- noctalia-shell &

#############################
### ENVIRONMENT VARIABLES ###
#############################

#uwsm users should avoid placing environment variables in the hyprland.conf file. Instead, use ~/.config/uwsm/env for theming, xcursor!
# See https://wiki.hyprland.org/Configuring/Environment-variables/
#env = GTK_THEME,Tokyo-Night-Dark
#env = GTK_ICON_THEME,Adwaita
#env = XCURSOR_SIZE,36
#env = HYPRCURSOR_SIZE,36
#env = XDG_CURRENT_DESKTOP,Hyprland
#env = XDG_SESSION_TYPE,wayland
