cursor #efdfd9
cursor_text_color #d9c2b7

foreground            #efdfd9
background            #19120e
selection_foreground  #482917
selection_background  #eebca3
url_color             #ffb690

color0   #19120e
color1   #ff7872
color2   #96ff7f
color3   #ffe572
color4   #f29f73
color5   #763817
color6   #ffb690
color7   #fff5ef
color8   #a59d99
color9   #ffa39f
color10  #b6ffa5
color11  #ffeea5
color12  #ffc0a0
color13  #ffcbb1
color14  #ffdecd
color15  #fffaf8
