cursor #f2dde0
cursor_text_color #dcbfc4

foreground            #f2dde0
background            #1b1113
selection_foreground  #51202d
selection_background  #fcb3c1
url_color             #ffb1c1

color0   #1b1113
color1   #ff7276
color2   #9dff7f
color3   #ffe272
color4   #f299ab
color5   #763341
color6   #ffb1c1
color7   #ffeff2
color8   #a5999b
color9   #ff9fa1
color10  #bbffa5
color11  #ffeca5
color12  #ffbcca
color13  #ffc8d3
color14  #ffdbe3
color15  #fff8f9
