cursor #ebe0e2
cursor_text_color #d4c2c7

foreground            #ebe0e2
background            #171214
selection_foreground  #402a32
selection_background  #e0bec8
url_color             #f7b4cc

color0   #171214
color1   #ff7278
color2   #9af77b
color3   #ffe172
color4   #ea9eb9
color5   #72394d
color6   #f7b4cc
color7   #ffeff5
color8   #a09498
color9   #ff9fa3
color10  #bcffa5
color11  #ffeca5
color12  #ffc4d9
color13  #ffcedf
color14  #ffdfeb
color15  #fff8fa
